const fs=require('fs'),assert=require('assert');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.setContent(fs.readFileSync('tank-play.html','utf8'));
  assert.match(await page.locator('.feedback').getAttribute('href'),/^mailto:chibachaseygaming@gmail.com/);
  await page.click('#infantry');
  assert.equal(await page.locator('#weaponClass option').count(),10);
  assert.equal(await page.evaluate(()=>weapons.length),100);
  await page.selectOption('#uniformSelect','2');
  await page.selectOption('#skinSelect','3');
  await page.selectOption('#helmetSelect','2');
  await page.selectOption('#finishSelect','1');
  await page.click('#deployInfantry');
  await page.waitForFunction(()=>document.pointerLockElement===document.getElementById('game'));
  await page.waitForFunction(()=>getComputedStyle(document.getElementById('game')).cursor==='none');
  assert.equal(await page.locator('#game').evaluate(e=>getComputedStyle(e).cursor),'none');
  await page.evaluate(()=>{enemies=[];infantryLook({movementX:Math.PI*4/.0025,movementY:0});});
  assert.ok(await page.evaluate(()=>lookYaw>Math.PI*2));
  await page.keyboard.down('w');await page.waitForTimeout(180);await page.keyboard.up('w');
  assert.ok(await page.evaluate(()=>Math.hypot(player.x,player.z)>.1));
  await page.evaluate(()=>{lookYaw=0;lookPitch=0;enemies=[{x:player.x,z:player.z+12,a:0,t:0,hp:100,max:100,cd:99}];fire(player);});
  assert.ok(await page.evaluate(()=>enemies[0].hp<100));
  await page.evaluate(()=>{lookYaw=Math.atan2(1,12);enemies[0].hp=100;fire(player);});
  assert.equal(await page.evaluate(()=>enemies[0].hp),100,'Shots beside a soldier must miss');
  await page.evaluate(()=>{lookYaw=0;faces=[];soldier(enemies[0]);});
  assert.ok(await page.evaluate(()=>faces.length>50&&faces.length<200&&faces.every(f=>f.pts.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)))),'Soldier mesh renders within budget');
  await page.evaluate(()=>drawWeapon());
  assert.ok(await page.evaluate(()=>faces.length>50&&faces.every(f=>f.pts.every(p=>Number.isFinite(p.vz)))),'Weapon uses 3D perspective vertices');
  await page.keyboard.press('Escape');
  await page.waitForFunction(()=>!document.pointerLockElement);
  await page.click('#resume');
  await page.waitForFunction(()=>document.pointerLockElement===document.getElementById('game'));
  await page.evaluate(()=>{lookPitch=1.2;enemies[0].hp=100;fire(player);});
  assert.equal(await page.evaluate(()=>enemies[0].hp),100,'Looking above an enemy must miss');
  await page.evaluate(()=>{lookPitch=0;});
  await page.evaluate(()=>{enemies=[{x:0,z:12,a:0,t:0,hp:0,max:65,cd:99},{x:0,z:16,a:0,t:0,hp:0,max:65,cd:99}];update(.01);});
  assert.equal(await page.evaluate(()=>state),'playing','Infantry kills do not open upgrades');
  assert.equal(await page.locator('#draftProgress').isVisible(),false);
  assert.equal(await page.evaluate(()=>blocked(20,0)),true,'Buildings block movement');
  assert.ok(await page.evaluate(()=>coverDistance(0,1.7,0,1,0,0,100)<20),'Buildings block shots');
  await page.evaluate(()=>{enemies=[{x:0,z:12,a:Math.PI,t:Math.PI,hp:100,max:100,cd:99}];lookYaw=0;lookPitch=0;draw();});
  await page.screenshot({path:'infantry-test.png'});
  await page.evaluate(()=>menu());await page.click('#deploy');
  assert.equal(await page.evaluate(()=>mode),'tank');
  assert.equal(await page.evaluate(()=>document.pointerLockElement),null);
  assert.deepEqual(errors,[]);
  console.log('PASS browser: 100-weapon loadout, customization, feedback, pointer lock, 720-degree look, movement, damage, pause/resume, uninterrupted infantry combat, cover and tank switching; no JS errors.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
