const fs = require('fs'), vm = require('vm'), assert = require('assert');
const elements = new Map();
const context = new Proxy({}, {get: (_, k) => (k === 'createRadialGradient' || k === 'createLinearGradient') ? () => ({addColorStop(){}}) : () => {}});
const element = id => { if (!elements.has(id)) elements.set(id, {hidden:false, innerHTML:'', getContext:()=>context, addEventListener(){}}); return elements.get(id); };
const saved = {};
const sandbox = {console, Math, Set, innerWidth:1200, innerHeight:800, devicePixelRatio:1, addEventListener(){}, requestAnimationFrame(){}, document:{getElementById:element,querySelectorAll:()=>[],addEventListener(){}}, localStorage:{getItem:k=>saved[k],setItem:(k,v)=>saved[k]=v}};
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync('tank-play.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1], sandbox);
const run = s => vm.runInContext(s, sandbox);
assert.equal(run('state'),'menu');
run('start();draw()');
assert.equal(run('enemies.length'),4);
run('enemies[0].hp=0;enemies[1].hp=0;update(.01)');
assert.equal(run('state'),'upgrade');
assert.equal(run('choices.length'),3);
assert.equal(run('profile.xp'),50);
run('pick(0)');assert.equal(run('state'),'playing');
run('pause()');assert.equal(run('state'),'paused');
run('resume();player.hp=-10;update(.01)');assert.equal(run('state'),'dead');
run('menu();start()');assert.equal(run('kills'),0);assert.equal(run('profile.xp'),50);
run('profile.points=1;profile.levels[0]=1;save();start()');assert.equal(run('player.max'),135);
run('player.levels=upgrades.map(u=>u.max===Infinity?0:u.max);draft()');assert.equal(run('choices.length'),3);
run('pick(0);for(let i=0;i<300;i++){if(state!=="playing")break;update(.016);draw();}');
assert.ok(JSON.parse(saved['iron-dune-v1']).xp>=50);
console.log('PASS: menu, rendering, combat, two-kill draft, three choices at max level, pause, death, restart, persistent XP and permanent armour.');
run('start();keys.add("w");update(.016);keys.clear()');
assert.ok(Math.abs(run('player.leftTravel'))>0);
const travel=run('player.leftTravel');run('update(.016)');assert.equal(run('player.leftTravel'),travel);
run('fire(player)');assert.equal(run('player.recoil'),1);
run('update(.1)');assert.ok(run('player.recoil')>0&&run('player.recoil')<1);
run('update(.2)');assert.equal(run('player.recoil'),0);
run('fire(enemies[0],true);draw()');assert.equal(run('enemies[0].recoil'),1);
console.log('PASS: movement-driven tracks, stationary tracks, player/enemy recoil, recovery, animated geometry rendering.');
