const fs = require('fs'), vm = require('vm'), assert = require('assert');
const elements = new Map();
const context = new Proxy({}, {get: (_, k) => (k === 'createRadialGradient' || k === 'createLinearGradient') ? () => ({addColorStop(){}}) : () => {}});
const element = id => { if (!elements.has(id)) elements.set(id, {hidden:false, innerHTML:'', getContext:()=>context, addEventListener(){}}); return elements.get(id); };
const saved = {};
const sandbox = {console, Math, Set, innerWidth:1200, innerHeight:800, devicePixelRatio:1, addEventListener(){}, requestAnimationFrame(){}, document:{getElementById:element,querySelectorAll:()=>[],addEventListener(){}}, localStorage:{getItem:k=>saved[k],setItem:(k,v)=>saved[k]=v}};
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync('tank-play.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1], sandbox);
const run = s => vm.runInContext(s, sandbox);
assert.equal(run('state'),'menu');
run('start();draw()');
assert.equal(run('enemies.length'),4);
run('enemies[0].hp=0;enemies[1].hp=0;update(.01)');
assert.equal(run('state'),'upgrade');
assert.equal(run('choices.length'),3);
assert.equal(run('profile.xp'),50);
run('pick(choices.findIndex(i=>upgrades[i].name!=="Battlefield salvage"))');assert.equal(run('state'),'playing');
run('pause()');assert.equal(run('state'),'paused');
run('resume();player.hp=-10;update(.01)');assert.equal(run('state'),'dead');
run('menu();start()');assert.equal(run('kills'),0);assert.equal(run('profile.xp'),50);
run('profile.points=1;profile.levels[0]=1;save();start()');assert.equal(run('player.max'),135);
run('player.levels=upgrades.map(u=>u.max===Infinity?0:u.max);draft()');assert.equal(run('choices.length'),3);
run('pick(0);for(let i=0;i<300;i++){if(state!=="playing")break;update(.016);draw();}');
assert.ok(JSON.parse(saved['iron-dune-v1']).xp>=50);
console.log('PASS: menu, rendering, combat, two-kill draft, three choices at max level, pause, death, restart, persistent XP and permanent armour.');
run('start();keys.add("w");update(.016);keys.clear()');
assert.ok(Math.abs(run('player.leftTravel'))>0);
const travel=run('player.leftTravel');run('update(.016)');assert.equal(run('player.leftTravel'),travel);
run('fire(player)');assert.equal(run('player.recoil'),1);
run('update(.1)');assert.ok(run('player.recoil')>0&&run('player.recoil')<1);
run('update(.2)');assert.equal(run('player.recoil'),0);
run('fire(enemies[0],true);draw()');assert.equal(run('enemies[0].recoil'),1);
console.log('PASS: movement-driven tracks, stationary tracks, player/enemy recoil, recovery, animated geometry rendering.');
run('globalThis.steeringTest={a:0};steerTank(steeringTest,Math.PI/2,1/60)');
assert.ok(run('steeringTest.a')>0&&run('steeringTest.a')<.01,'Turn starts gradually');
run('for(let i=0;i<180;i++)steerTank(steeringTest,Math.PI/2,1/60)');
assert.ok(Math.abs(run('steeringTest.a')-Math.PI/2)<.01,'Turn settles on target');
run('steeringTest={a:Math.PI-.01};steerTank(steeringTest,-Math.PI+.1,1/60)');
assert.ok(run('steeringTest.a')>Math.PI-.01,'Turn crosses angle boundary along shortest arc');
run('start();cam=0;keys.add("d");update(1/60);keys.clear();draw()');
assert.ok(Math.abs(run('player.x'))<Math.abs(run('player.z')),'Movement follows hull through the turn');
assert.ok(run('faces.every(f=>f.pts.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)&&Number.isFinite(p.d)))'),'Detailed mesh vertices remain finite');
console.log('PASS: gradual steering, target settling, angle wrapping, hull-aligned movement and detailed geometry.');
run('faces=[];tank(player);globalThis.playerFaces=faces.length;faces=[];tank(player,true)');
assert.ok(run('faces.length<playerFaces*.4'),'Enemy geometry stays substantially cheaper than the player');
assert.equal(run('visible(player.x+10000,player.z+10000)'),false,'Offscreen tanks are culled');
assert.equal(run('shadeColor("#ffffff",1)'),'rgb(255,255,255)');
console.log('PASS: enemy geometry budget, offscreen culling and cached shading.');
run('menu();profile.xp=0;rebirthMenu()');
assert.equal(run('performRebirth()'),false,'Rebirth locked below required level');
run('profile.xp=1800;profile.points=4;profile.levels=[2,3,1];profile.best=42;profile.kills=99;rebirthMenu();menu()');
assert.equal(run('profile.xp'),1800,'Cancelling preserves progress');
run('rebirthMenu();performRebirth()');
assert.equal(run('profile.rebirths'),1);
assert.equal(run('profile.xp'),0);
assert.equal(run('profile.points'),0);
assert.equal(run('profile.levels.join()'),'0,0,0');
assert.equal(run('profile.best'),42);
assert.equal(run('profile.kills'),99);
assert.equal(run('rebirthRequirement()'),15);
assert.equal(run('performRebirth()'),false,'Duplicate confirmation cannot rebirth again');
run('crew=1;start();earnXP(25)');
assert.equal(run('player.max'),132);
assert.equal(run('player.damage'),44);
assert.equal(run('profile.xp'),30);
const reloaded=vm.createContext({...sandbox});
vm.runInContext(fs.readFileSync('tank-play.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1],reloaded);
assert.equal(vm.runInContext('profile.rebirths',reloaded),1,'Rebirth survives reload');
console.log('PASS: rebirth unlock, cancellation, resets, retained records, bonuses, repeat protection and save reload.');
assert.equal(run('weapons.length'),100);
assert.equal(run('new Set(weapons.map(w=>w.name)).size'),100);
run('mode="infantry";for(let i=0;i<100;i++){loadout.weapon=i;start();if(player.damage!==weapons[i].damage*rebirthPower()||player.reload!==weapons[i].interval)throw Error("Weapon stats mismatch");drawWeapon();}');
run('enemies=[{x:0,z:12,a:0,t:0,hp:0,cd:99},{x:0,z:14,a:0,t:0,hp:0,cd:99}];update(.01)');
assert.equal(run('state'),'playing');
assert.equal(run('drafts'),0);
run('globalThis.collider={x:13,z:0};moveFoot(collider,20,0)');
assert.equal(run('collider.x'),13);
assert.ok(run('coverDistance(0,1.7,0,1,0,0,100)')<20);
run('loadout.weapon=73;loadout.uniform=2;loadout.skin=3;loadout.helmet=2;loadout.finish=1;saveLoadout()');
const loadoutReload=vm.createContext({...sandbox});
vm.runInContext(fs.readFileSync('tank-play.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1],loadoutReload);
assert.equal(vm.runInContext('JSON.stringify(loadout)',loadoutReload),run('JSON.stringify(loadout)'));
console.log('PASS: all 100 weapons equip/render with correct stats, no infantry draft, cover collision and saved customization.');
run('mode="infantry";loadout.soldierClass=0;loadout.difficulty=0;start();globalThis.easyEnemyHP=enemies[0].hp;globalThis.easyCount=enemies.length;globalThis.easyHealth=player.max;globalThis.easySpeed=player.speed;');
run('loadout.difficulty=3;start()');
assert.ok(run('enemies[0].hp>easyEnemyHP&&enemies.length>easyCount'));
run('loadout.soldierClass=3;start()');
assert.ok(run('player.max>easyHealth&&player.speed<easySpeed'));
run('loadout.soldierClass=1;start()');
assert.ok(run('player.max<easyHealth&&player.speed>easySpeed'));
run('loadout.soldierClass=2;start()');
assert.equal(run('player.regen'),2);
run('saveLoadout()');
const settingsReload=vm.createContext({...sandbox});
vm.runInContext(fs.readFileSync('tank-play.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1],settingsReload);
assert.equal(vm.runInContext('loadout.soldierClass',settingsReload),2);
assert.equal(vm.runInContext('loadout.difficulty',settingsReload),3);
run('mode="tank";start()');assert.equal(run('enemies.length'),4);
assert.equal(run('difficultySettings().damage'),1,'Infantry difficulty does not affect tanks');
console.log('PASS: difficulty enemy stats/count, four soldier classes, saved class/difficulty and tank isolation.');

